### ISSUE TITLE
[Feature] Apply the same design of Weekly email to the rest emails

### ISSUE THREAD

**Issue by chm1975** [protofire/livepeer-alerts-backend#105]
**To Do:**
- We have a new design on the Weekly notification email. We need to apply the same header and footer to the other emails.
- Take every email template on Sendgrid and update the design keeping the same body. Evaluate if we need to change the font or we can keep the same.

**Comment by mariano-aguero** [comment]
## Includes:
- Added on Sendgrid new versions of the notifications with the new template
- The new versions are inactive until deployment

@Agupane Can you validate the work is done? 

Regards
