### ISSUE TITLE
ETH Earned in Fees should contain a unit label or decimal

### ISSUE THREAD

**Issue by dob** [protofire/livepeer-alerts-backend#148]
The "ETH Earned in Fees" section on livepeer.tools shows a value in what I presume is wei. For example, it listed that the node had earned something like 4234857690. I think this should either be labeled as wei, or should be labeled as ETH and include a decimal to specify it's a very small portion of an ETH.

**Comment by Agupane** [comment]
Hi @dob, could you please share us some screenshots in order to reproduce the problem?. Thanks!

**Comment by Agupane** [comment]
This issue was clossed by [#119](https://github.com/protofire/livepeer-alerts-frontend/pull/119)
