### ISSUE TITLE
(Feature) Notificate Transcoder rules changes  to Delegator (NE)

### ISSUE THREAD

**Issue by chm1975** [protofire/livepeer-alerts-backend#49]
As Delegator, I want to be informed if my transcoders have changed the rules of Rewards.

* We need to estimate this: *
- How to detect the rules of my transcoder have changed
- How we can inform the change to the user
- Write the process here
- Estimate all work including the email template and sending function.

**Comment by mariano-aguero** [comment]
Solution already merged, and deployed in the release 1.2.0.
