### ISSUE TITLE
[Bug] Telegram bot is not always sending notifications

### ISSUE THREAD

**Issue by Agupane** [protofire/livepeer-alerts-backend#70]
For some reason, the telegram bot is not sending the notifications to all the suscribers. 

How to reproduce:
```
1. Subscribe to the bot
2. Wait for a round change and see if the bot sends the new round notification
```

**Comment by mariano-aguero** [comment]
Worker log:
![Screenshot_20190712_111418](https://user-images.githubusercontent.com/1144028/61135011-305e1580-a497-11e9-9edc-bccab0a1657f.png)

We can visualize in the log that on 11/07 the worker was working well. We will monitor errors, If no errors are reported, we will proceed to close the issue.

**Comment by Agupane** [comment]
The bot is working as expected, I'll close this issue.
