### ISSUE TITLE
[Feature] Be notified when the Pending > Bonded period has ended

### ISSUE THREAD

**Issue by chm1975** [protofire/livepeer-alerts-backend#75]
**Estimated time: to define**
**To Do:**
 Delegators, after bonding to a delegate, there is a period of 1 das/round that he must wait before to participate in the next round.
We need to add a new alert that sends a message to the user informing when the bond period is ready and Delegator can participate in the next round.

**Acceptance Criteria:**
- Delegator Bound to selected Delegate
- Bond period start
- After 1 day/round the Delegator receives an email notification about the waiting period is ready and he can participate in the next round.
 
**Links and resources:**

**Comment by mariano-aguero** [comment]
Task TODO:
- [ ] Send email notification
- [ ] Send telegram notification
