### ISSUE TITLE
[UI] Design Weekly Email Subscription with a summary

### ISSUE THREAD

**Issue by chm1975** [protofire/livepeer-alerts-backend#95]
**To Do:**
 - Create a new design of the Weekly subscription email adding a table with the all earned LPT by round
 - The backend must provide the rewards by round earned in the week for the Delegator

New design: https://docs.google.com/spreadsheets/d/1F8Ub8PfuCvhhnDs_Y5bRaJuFZj5-drudBX4fGtCFeoQ/edit?usp=sharing
 
 
**Links and resources:**
Example of Adam´s email: https://files.slack.com/files-pri/T0250C1BN-FK823PKJN/image.png

**Related tickets:**
[protofire/livepeer-alerts-backend#82 (protofire/livepeer-alerts-backend#82)](https://zube.io/protofire/livepeer-staking-assistant/c/82) 
[protofire/livepeer-alerts-backend#78 (protofire/livepeer-alerts-backend#78)](https://zube.io/protofire/livepeer-staking-assistant/c/78)

**Comment by gabitoesmiapodo** [comment]
**Proposal:**

<img width="540" alt="Screen Shot 2019-07-22 at 17 05 05" src="https://user-images.githubusercontent.com/4015436/61661684-0977be80-aca3-11e9-9b90-72182344810d.png">


**Zeplin:** https://app.zeplin.io/project/5b71fb9cd86c791b1612c035/screen/5d361693d68d9d40fe185155

**Comment by chm1975** [comment]
@Gabriel-Rodriguez The proposal design is good! Go ahead!
